### ISSUE TITLE
⚡ Repository standardization

### ISSUE THREAD

**Issue by luxonauta** [dracula/plsql-developer#2]
Hi @emir-karpuz, we need to adjust a few things first to move forward, ok? ✨

First, we need to update the screenshot! Can you take a single capture at the closest possible resolution to 1728x1117?

We also need a separate .md with installation instructions to show the theme on the site.

I ask for these changes to standardize with the other repositories, [see an example](https://github.com/dracula/notepad-plus-plus); this is also important because it helps other potential users who would like to contribute too! 😁

Let me know if something isn't possible or if you have any questions! 🙂

**Comment by emir-karpuz** [comment]
Hello @luxonauta,
I hope you are doing great, sorry for late reply cuz i was busy for my daily work routine. I tried to follow the advices you are giving to me. I couldn't make ss bigger but i did others. Please take a look at and let me know if you need anything 🙂

**Comment by luxonauta** [comment]
No problem, I understand! 💖 I'll make a few more adjustments and put it up for the next wave!
